[tool.poetry]
name = "multisig_ci"
version = "0.3.2"
description = "Gnosis safe ci scripts."
authors = ["kx9x <kx9x@protonmail.com>"]
license = "AGPLv3"
packages = [
    { include = "multisig_ci" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
eth_brownie = "1.19"
safe-eth-py = "4.0.1"
ape_safe = "0.5.0"
tenacity = "8.0.1"
psutil = "5.9.1"
requests = "2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
